On the testing machines we use the default lammps

diff --git a/source_me b/source_me
--- a/source_me
+++ b/source_me
@@ -52,18 +52,18 @@ export PATH=$PYLMPSPATH/scripts:$PATH
 #
 # We assume default location for lammps and so on....
 #
-LAMMPSPATH=/home/$USER/sandbox/lammps/python
-if [ -d $LAMMPSPATH ]; then 
-  export PYTHONPATH=LAMMPSPATH:$PYTHONPATH
-else
-  echo "Missing lammps installation"
-  exit 1
-fi
-
-LAMMPSPOT=/home/$USER/sandbox/lammps/potentials
-if [ -d $LAMMPSPOT ]; then
-   export REAXFF_FILES=$LAMMPSPOT
-else
-  echo "Missing lammps potentials"
-  exit 1
-fi
+#LAMMPSPATH=/home/$USER/sandbox/lammps/python
+#if [ -d $LAMMPSPATH ]; then 
+#  export PYTHONPATH=LAMMPSPATH:$PYTHONPATH
+#else
+#  echo "Missing lammps installation"
+#  exit 1
+#fi
+#
+#LAMMPSPOT=/home/$USER/sandbox/lammps/potentials
+#if [ -d $LAMMPSPOT ]; then
+#   export REAXFF_FILES=$LAMMPSPOT
+#else
+#  echo "Missing lammps potentials"
+#  exit 1
+#fi
